[package]
name = "edigeo"
authors = ["Paul Duvenage <duvenagep@gmail.com>"]
version = "0.1.1"
edition = "2021"
license = "MIT"

[dependencies]
bzip2 = "0.4.4"
encoding_rs = "0.8.34"
encoding_rs_io = "0.1.7"
tar = "0.4.43"
thiserror = "1.0.65"
